### ISSUE TITLE
Failing reporting

### ISSUE THREAD

**Issue by exotlv** [zealous-tech/testrail-reporter#8]
`TestRail Reporter Log: The reporter started successfully!
TestRail Reporter Log: The Run started, utilizing an existing run in TestRail with the ID=2211.
D:\tests-ui\node_modules\@zealteam\testrail-reporter\src\reporters\caller-playwright.js:147
        const stepsDoMatch = testRailCaseSteps.length === resultSteps.length;
                                               ^

TypeError: Cannot read properties of undefined (reading 'length')
    at CallerPlaywright.stepResultComment (D:\tests-ui\node_modules\@zealteam\testrail-reporter\src\reporters\caller-playwright.js:147:48)
    at CallerPlaywright.onTestEnd (D:\tests-ui\node_modules\@zealteam\testrail-reporter\src\reporters\caller-playwright.js:91:18)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at PlaywrightTestRailReporter.onTestEnd (D:\tests-ui\node_modules\@zealteam\testrail-reporter\index.js:41:9)
`

**Comment by arayik-chaparyan-im** [comment]
Thank you @exotlv for reporting this issue !
We plan to fix it within a week.

**Comment by gevorg-vardanyan-im** [comment]
Hi @exotlv .
Could you please provide more details in order to reproduce and debug this issue ?
Also it would be helpful to have a details mentioned in your testrail.config.js file.

**Comment by gevorg-vardanyan-im** [comment]
Hi @exotlv , we just released the new version of reporter - 1.0.7 version.
It should fix your issues.
Please test with it and let us know.
Thanks in advance.

**Comment by arayik-chaparyan-im** [comment]
Due to the lack of response from the @exotlv over a 2 weeks period, we consider the issue resolved. Closing the issue.
